    import 'expose?jQuery!jquery';
    import 'expose?$!jquery';
    import './utility/tools.js';
    import './utility/helpers.js';
    import 'bootstrap';
    import 'icheck';
    import 'chart.js';
    import './../../assets/js/custom.js';
    import 'datatables';
    import './../../assets/js/datatables/tools/js/dataTables.tableTools.js';
    import 'select2/dist/js/select2.full.min.js';
    import './../../assets/css/select/select2.min.css';
    import 'ui-select';
    import 'angular-sanitize';
    // import './../../assets/js/autocomplete/countries.js';
    import 'devbridge-autocomplete';
